name: ZMusicBox
version: 2.6.0
api: [1.0.0, 2.0.0, 2.1.0, 3.0.0, 3.0.1, 4.0.0, 3.0.0-ALPHA5, 3.0.0-ALPHA6]
author: Zzm
description: Play music in your server
main: ZMusicBox\ZMusicBox

commands:
 music:
  permission: ZMusicBox.music
  description: Manage the music in your server
  usage: /music <start|stop|next>

permissions:
 ZMusicBox:
  default: op
  description: ZMusicBox Commands
  children:
     ZMusicBox.music:
      default: op
      description: ZMusicBox Commands
    
